services:
  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: lumo-postgres
    restart: always
    environment:
      POSTGRES_USER: lumo_user
      POSTGRES_PASSWORD: lumo_password
      POSTGRES_DB: lumo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/src/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lumo_user -d lumo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: lumo-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
